apiConfig:
  prototl: "HTTP"
  basePath: "/finance/v1/"
  configPath: "/services"
  port: "9091"
  
autoDiscoveryId: "19770728" 
 
mongo:
  host: "olympusplatformcluster1.cggcwqu.mongodb.net"
  port: "27017"
  cluster:
    name: "OlympusPlatformCluster1"
  databases:
    finance: 
      name: "finance"
      connectionString: mongodb+srv://${secure::mongo.username}:${secure::mongo.password}@${mongo.host}/${mongo.databases.finance.name}?retryWrites=true&w=majority&appName=${mongo.cluster.name}
      collections:
        currency: "currency"
        coins: "coins"
        banks: "banks"
        reserve: "reserve"
        accounts: "accounts"
    chatbot: 
      name: "chatbot"
      connectionString: mongodb+srv://${secure::mongo.username}:${secure::mongo.password}@${mongo.host}/${mongo.databases.chatbot.name}?retryWrites=true&w=majority&appName=${mongo.cluster.name}
      collections:
        users: "users"
    olympus: 
      name: "olympus"
      connectionString: mongodb+srv://${secure::mongo.username}:${secure::mongo.password}@${mongo.host}/${mongo.databases.chatbot.name}?retryWrites=true&w=majority&appName=${mongo.cluster.name}
      collections:
        users: "users"
        
#secure.key: P2@RGa+z$88ezN3w7O[71Q%i
